package rules


import com.chat.bot.pao.model.dto.ChatDTO; 


global com.chat.bot.pao.model.dto.ChatDTO chat

rule "Your First Rule"

    when
        chatInstance:ChatDTO(solicitud == "hola");
        
    then
		chat.setRespuesta("Hola mi nombre es books. ¿Como te llamas?");
end

rule "nombre"

    when
        chatInstance:ChatDTO(solicitud == "paola"||solicitud == "andrea"||solicitud == "julian"||solicitud == "sofia"||solicitud == "alberto"||solicitud == "ruben"
        ||solicitud == "raul"||solicitud == "damian"||solicitud == "domenico"||solicitud == "hermen"||solicitud == "jose"||solicitud == "josé"||solicitud == "ricardo"
        ||solicitud == "adonis"||solicitud == "leandro"||solicitud == "leonardo"||solicitud == "francisco"||solicitud == "ana"||solicitud == "maria"||solicitud == "camila"
        ||solicitud == "veronica"||solicitud == "sandra"||solicitud == "johana"||solicitud == "ruben"||solicitud == "Ruben"||solicitud == "elisabeth"||solicitud == "elizabeth"||solicitud == "eliza"
        ||solicitud == "valentina"||solicitud == "lucas"||solicitud == "damaso"||solicitud == "hermenegildo"||solicitud == "daniela"||solicitud == "laura"||solicitud == "enrique");
        
    then
		chat.setRespuesta("Mucho gusto, que deseas buscar");
end

rule "conversation1"

    when
        chatInstance:ChatDTO(solicitud == "libros" || solicitud == "libro");
        
    then
		chat.setRespuesta("Que tipo libro o libros buscas");
end

rule "conversation2"

    when
        chatInstance:ChatDTO(solicitud == "libros de ciencia ficción"||solicitud == "ficción"||solicitud == "ciencia"||solicitud == "romance"||solicitud == "historicos"||solicitud == "historia"
         ||solicitud == "ciencia ficcion"||solicitud == "romantica" || solicitud == "drama" || solicitud == "libros dramaticos" || solicitud == "libros educativos"
         ||solicitud == "educación" || solicitud == "educacion" || solicitud == "sistemas" || solicitud == "informatica"
         ||solicitud == "novelas de drama" || solicitud == "poesia" || solicitud == "cuentos infantiles" || solicitud == "infantiles"
         ||solicitud == "politicos" || solicitud == "libros sobre politica" || solicitud == "eroticos" || solicitud == "libros eroticos"||solicitud == "libros");
         
        
    then
		chat.setRespuesta("Tienes preferencia por algún autor");
end

rule "conversation3"

    when
        chatInstance:ChatDTO(solicitud == "no");
        
    then
		chat.setRespuesta("Puedes visualizar una lista de libros de acuerdo a tu solicitud");
end	

rule "conversation4"
    when
        chatInstance:ChatDTO(solicitud == "si");
        
    then
		chat.setRespuesta("Que autor es tu favorito");
	
end	

rule "conversation5" 	
 	when
        chatInstance:ChatDTO(solicitud == "jk-rouling"||solicitud == "dan brown"
        ||solicitud == "fernando gamboa"||solicitud == "cristian perfumo"||solicitud == "cristian"
        ||solicitud == "fernando"||solicitud == "mercedes pinto maldonado	"||solicitud == "mercedes"
        ||solicitud == "pinto"||solicitud == "maldonado"||solicitud == "jk"
        ||solicitud == "rouling"||solicitud == "carmen mola"||solicitud == "carmen"
        ||solicitud == "mola"||solicitud == "susana"||solicitud == "martinez"
        ||solicitud == "susana martinez"||solicitud == "dan" ||solicitud == "brown");
        
    then
		chat.setRespuesta("Puedes visualizar una lista de libros de acuerdo a tu solicitud");

end	